name: BedWars
version: 1.0
main: com.github.devil0414.bedwars.plugin.BedWarPlugin
api-version: 1.16
authors: [devil0414]
depend: [Tap, Kotlin, InvFX]
commands:
  bw:
    permission: command.bw
permissions:
  command.bw:
    default: op